### ISSUE TITLE
Authentication error when running playbooks against FTD v 6.2.3

### ISSUE THREAD

**Issue by ncoutinho1** [CiscoDevNet/FTDAnsible#64]
Hello,
 I am unable to get the playbooks to work and get this error when running .

TASK [Gathering Facts] 
FAILED! => {"msg": "Server returned an error during authentication request: {'code': 404, 'description': 'The server has not found anything matching the request URI', 'homeRef': '/', 'reasonPhrase': 'Not Found', 'uri'

Rest api has been enabled on the FTD.
Using connection: httpapi

**Comment by annikulin** [comment]
Hello @ncoutinho1,

First of all, thank you for opening the issue. Based on the error, you need to override the value for `ansible_httpapi_ftd_token_path` property in the inventory file. By default, it is set to `/api/fdm/v2/fdm/token` that suits FTD v6.3, but for FTD v6.2.3, it should be `/api/fdm/v1/fdm/token`.

So, your inventory file for FTD v6.2.3 might look like this:
```
[ftd]
ftd-6.2.3 ansible_host=192.168.1.1 ansible_port=443 ansible_network_os=ftd ansible_user=admin ansible_password=123qwe ansible_httpapi_ftd_token_path=/api/fdm/v1/fdm/token
```
Also, you can find more information in the [docs about inventory files](https://developer.cisco.com/site/ftd-ansible/#!installation-guide/creating-inventory). 

Please, let us know if it fixes the issue.

**Comment by sdbrain** [comment]
@ncoutinho1 these modules are for FTD API. I think you are trying to use them to configure FMC and that wont work.
FTD API can be enabled by running *configure manager local* from clish on your FTD..
