### ISSUE TITLE
Sample configuration of route entry

### ISSUE THREAD

**Issue by StephenColby** [CiscoDevNet/FTDAnsible#92]
Can a sample route entry playbook be provided?  Also in the example should be multiple network objects to show proper syntax of that for networks and gateway (single object).  I am working on building a playbook for it now but have run into a few issues.  When I look at the required field for upsertStaticRouteEntry it requires 2 path parameters in addition to the data parameters.

Parameter | Required | Type | Description
-- | -- | -- | --
parentId | True | string |  
objId | True | string

The parent ID makes some sense in terms of the StaticRouteEntryContainer exposed by the API (even though there is only one...assuming this is to easily accommodate multiple routing tables later?) however why would an objectid also be required for an upsert operation?

**Comment by 119Vik** [comment]
@StephenColby I've just add PR #94  with update static_route_entry sample playbook. 
**objId** is not required in the playbook, it's a mistake in the docs which will be fixed soon.
To specify route object which should be updated during update please use **filters** section of the **ftd_configuration** module.
